services:
  - type: web
    name: web-app
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: your_secret_key_change_in_production_12345
      - key: ALLOWED_ORIGINS
        value: https://web-app-kljr.onrender.com